services:
  coursemanage.api:
    image: ${DOCKER_REGISTRY-}coursemanage.api
    container_name: coursemanage.api
    depends_on:
       coursemanage.database:
         condition: service_healthy
       coursemanage.logging:
         condition: service_started
    build:
      context: .
      dockerfile: Web.API/Dockerfile
    volumes:
      - ./app_logs:/app/logs

  coursemanage.database:
    image: postgres:latest
    container_name: coursemanage.database
    restart: always
    environment:
      - POSTGRES_DB=coursemanage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
       - ./app_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coursemanage"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  coursemanage.logging:
    image: datalust/seq:latest
    container_name: coursemanage.logging
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5004:80
  