// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250322103115_UpdateSeed")]
    partial class UpdateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("519bc5a9-8bc3-495b-a320-4afaee4cd363"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("214e0c6b-e213-40d1-a1f2-169b0026f882"),
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("dcc31107-75b5-4504-8e87-0d654323c56d"),
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email_verification_token_hash");

                    b.Property<DateTime?>("EmailVerificationTokenHashExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_hash_expires");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("RefreshTokenExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("refresh_token_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8c35758-1881-47ad-8994-0529df7c70ed"),
                            Email = "admin@test.com",
                            IsEmailVerified = true,
                            Name = "Admin",
                            PasswordHash = "$2a$13$GFEm2Ijr3Jd4GsbRXp8Yn.YVrCAoatoFjfm458GFMpd5UFzyShqCq"
                        },
                        new
                        {
                            Id = new Guid("ee13b6c6-a98e-440b-93f8-ecf083d51052"),
                            Email = "staff@test.com",
                            IsEmailVerified = true,
                            Name = "Staff",
                            PasswordHash = "$2a$13$902uxeLjnX9nd.78KtdZNOUQNrzoCGvdug1dUiV33NRNNblqe7VA6"
                        },
                        new
                        {
                            Id = new Guid("2e23583f-d118-4295-8a80-09266b7497db"),
                            Email = "student@test.com",
                            IsEmailVerified = true,
                            Name = "Student",
                            PasswordHash = "$2a$13$7ZX.H.wI0yitiqiHnE9D8Om.T6F0boCdYS5EmKviXkl7m8uwefY4e"
                        });
                });

            modelBuilder.Entity("Domain.Relationships.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b8c35758-1881-47ad-8994-0529df7c70ed"),
                            RoleId = new Guid("519bc5a9-8bc3-495b-a320-4afaee4cd363")
                        },
                        new
                        {
                            UserId = new Guid("ee13b6c6-a98e-440b-93f8-ecf083d51052"),
                            RoleId = new Guid("214e0c6b-e213-40d1-a1f2-169b0026f882")
                        },
                        new
                        {
                            UserId = new Guid("2e23583f-d118-4295-8a80-09266b7497db"),
                            RoleId = new Guid("dcc31107-75b5-4504-8e87-0d654323c56d")
                        });
                });

            modelBuilder.Entity("Domain.Relationships.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
